type Query {
	search(id: String!): SearchResult
}
type SearchResult {
	stream: [Stream]
	adaptive: [Adaptive]
	meta: Meta
}
type Stream {
	s: String
	itag: String
	url: String
	type: String
	quality: String
	sp: String
}
type Adaptive {
	lmt: String
	xtags: String
	clen: String
	projection_type: String
	quality_label: String
	type: String
	url: String
	sp: String
	itag: String
	s: String
	init: String
	size: String
	index: String
	fps: String
	bitrate: String
}
type Meta {
	player_response: String
	itct: String
	adaptive_fmts: String
	account_playback_token: String
	of: String
	no_get_video_log: String
	apply_fade_on_midrolls: String
	cr: String
	avg_rating: String
	show_content_thumbnail: String
	cver: String
	oid: String
	fmt_list: String
	cl: String
	midroll_prefetch_size: String
	enabled_engage_types: String
	allow_html5_ads: String
	video_id: String
	ssl: String
	vm: String
	serialized_ad_ux_config: String
	xhr_apiary_host: String
	tmi: String
	eventid: String
	iv3_module: String
	ad_logging_flag: String
	csi_page_type: String
	thumbnail_url: String
	keywords: String
	innertube_context_client_version: String
	midroll_freqcap: String
	apiary_host_firstparty: String
	gapi_hint_params: String
	apiary_host: String
	innertube_api_version: String
	ad_preroll: String
	token: String
	fade_in_start_milliseconds: String
	vss_host: String
	tag_for_child_directed: String
	mpu: String
	ptchn: String
	iv_load_policy: String
	fade_out_start_milliseconds: String
	player_error_log_fraction: String
	atc: String
	hl: String
	idpj: String
	iv_invideo_url: String
	is_listed: String
	fade_out_duration_milliseconds: String
	videostats_playback_base_url: String
	fexp: String
	ptk: String
	fflags: String
	allow_ratings: String
	vmap: String
	ucid: String
	timestamp: String
	external_play_video: String
	watermark: String
	ad3_module: String
	title: String
	allow_embed: String
	ad_device: String
	pltype: String
	host_language: String
	t: String
	url_encoded_fmt_stream_map: String
	innertube_api_key: String
	author: String
	loudness: String
	storyboard_spec: String
	fade_in_duration_milliseconds: String
	rvs: String
	plid: String
	sffb: String
	c: String
	ldpj: String
	view_count: String
	allow_below_the_player_companion: String
	enablecsi: String
	status: String
	relative_loudness: String
	length_seconds: String
}
